export {
  ACTOR_TYPES,
  BUG_STATES,
  CONTRACT_VERSION,
  DOMAIN_VERSION,
  PRIORITIES,
  RELAY_AUTOMATION_TARGET_STATES,
  REPAIR_MODES,
  REPAIR_STATUSES,
  SEVERITIES,
  TERMINAL_BUG_STATES,
  VERIFICATION_STATUSES,
  isBugState,
  isRelayAutomationTargetState,
  isRepairMode,
  isRepairStatus,
  isTerminalBugState,
  isVerificationStatus,
} from "./statuses.js";

export type {
  ActorType,
  BugState,
  Priority,
  RepairMode,
  RepairStatus,
  Severity,
  VerificationStatus,
} from "./statuses.js";

export {
  DOMAIN_DECISION_ERROR_CODES,
  DOMAIN_EVENT_PAYLOAD_KEYS,
  DOMAIN_EVENT_PAYLOAD_MAX_BYTES,
  DOMAIN_EVENT_UUID_PAYLOAD_KEYS,
  DomainDecisionError,
  decideDomainCommand,
} from "./state-machine.js";

export type {
  BuildAggregate,
  BuildLineageEntryFact,
  BuildRepairLink,
  BuildRequirementAggregate,
  ClosureAcceptanceFact,
  CodeDeliveryCommand,
  CreateRepairAttemptCommand,
  CreateVerificationCommand,
  DomainActor,
  DomainBuildEvidenceOverrideAuthorityFact,
  DomainCommand,
  DomainDecision,
  DomainDecisionContext,
  DomainDecisionErrorCode,
  DomainEventPlan,
  DomainEventPayload,
  DomainEventPayloadKey,
  DomainOutboxPlan,
  DomainProjectActorFact,
  DomainProjectPolicy,
  DomainSnapshot,
  DuplicateFact,
  FailRepairAttemptCommand,
  LegacySupersedeRepairAttemptCommand,
  LinkBuildRepairCommand,
  MarkBugDuplicateCommand,
  NoCodeDeliveryCommand,
  OccurrenceFact,
  OccurrenceBuildLineageFact,
  RecordVerificationResultCommand,
  ReopenBugCommand,
  RepairAttemptAggregate,
  StartRepairAttemptCommand,
  StartVerificationCommand,
  SupersedeRepairAttemptCommand,
  TransitionBugCommand,
  VendorSupersedeRepairAttemptCommand,
  VerificationAggregate,
} from "./state-machine.js";
