/** Fixed HTTP adapters. No arbitrary URL, actor, credential, or filesystem execution. */
export const AUTOMATION_HTTP_ROUTES = [
  ["qa_get_session", "读取当前登录身份", "GET", "/api/v1/auth/me"],
  ["qa_logout", "退出当前会话", "POST", "/api/v1/auth/logout"],
  ["qa_get_project_entry", "读取项目登录入口", "GET", "/api/v1/project-entry/:projectId"],
  ["qa_list_managed_projects", "GM 读取全部项目", "GET", "/api/v1/gm/projects"],
  [
    "qa_list_management_events",
    "读取项目管理审计",
    "GET",
    "/api/v1/projects/:projectId/management-events",
  ],
  [
    "qa_link_identity",
    "关联人员姓名身份",
    "POST",
    "/api/v1/projects/:projectId/users/:userId/identity-link",
  ],
  [
    "qa_unlink_identity",
    "解除人员姓名关联",
    "DELETE",
    "/api/v1/projects/:projectId/users/:userId/identity-link",
  ],
  ["qa_get_metrics", "读取项目时间范围统计", "GET", "/api/v1/projects/:projectId/metrics/overview"],
  ["qa_list_notifications", "读取项目通知", "GET", "/api/v1/notifications"],
  [
    "qa_get_duplicate_candidates",
    "读取重复 Bug 候选",
    "GET",
    "/api/v1/bugs/:bugId/duplicate-candidates",
  ],
  ["qa_mark_duplicate", "标记重复 Bug 并保存理由", "POST", "/api/v1/bugs/:bugId/mark-duplicate"],
  ["qa_get_repair_attempt", "读取修复轮次", "GET", "/api/v1/repair-attempts/:attemptId"],
  [
    "qa_fail_repair_attempt",
    "将当前修复轮次标记为失败",
    "POST",
    "/api/v1/repair-attempts/:attemptId/fail",
  ],
  [
    "qa_supersede_repair_attempt",
    "原子替换当前修复轮次",
    "POST",
    "/api/v1/repair-attempts/:attemptId/supersede",
  ],
  [
    "qa_get_bug_workflow",
    "读取冻结工作流分页，query使用cursor和limitPerCollection",
    "GET",
    "/api/v1/bugs/:bugId/workflow",
  ],
  [
    "qa_get_relay_receipt",
    "读取 Relay 交付回执",
    "GET",
    "/api/v1/repair-attempts/:attemptId/relay-receipt",
  ],
  ["qa_get_verification", "读取人工验收记录", "GET", "/api/v1/verifications/:verificationId"],
  ["qa_list_build_records", "读取项目构建证据记录", "GET", "/api/v1/projects/:projectId/builds"],
  ["qa_create_build_record", "登记真实构建证据", "POST", "/api/v1/projects/:projectId/builds"],
  ["qa_get_build_record", "读取构建证据", "GET", "/api/v1/builds/:buildId"],
  ["qa_link_build_repair", "绑定构建证据与修复轮次", "POST", "/api/v1/builds/:buildId/link-repair"],
  ["qa_create_capture", "登记截图录屏与设备采集包", "POST", "/api/v1/capture-bundles"],
  ["qa_get_capture", "读取截图录屏与设备采集包", "GET", "/api/v1/capture-bundles/:captureId"],
  ["qa_init_upload", "创建附件分块上传会话", "POST", "/api/v1/uploads/init"],
  ["qa_finalize_upload", "校验并完成附件上传", "POST", "/api/v1/uploads/:sessionId/finalize"],
  ["qa_bind_attachment", "预留附件业务绑定", "POST", "/api/v1/attachments/:attachmentId/bind"],
  ["qa_get_packaging", "读取构建组件配置与状态", "GET", "/api/v1/packaging"],
  ["qa_list_build_tasks", "读取构建任务历史", "GET", "/api/v1/packaging/tasks"],
  ["qa_get_build_task", "读取构建任务证据与版本", "GET", "/api/v1/packaging/tasks/:id"],
  ["qa_get_build_progress", "读取构建实时进度", "GET", "/api/v1/packaging/progress"],
  ["qa_enqueue_build", "提交项目构建任务", "POST", "/api/v1/packaging/builds"],
  ["qa_resume_build", "恢复项目构建任务", "POST", "/api/v1/packaging/tasks/:id/resume"],
  ["qa_cancel_build", "取消项目构建任务", "POST", "/api/v1/packaging/tasks/:id/cancel"],
  ["qa_get_upload_status", "读取上传组件和队列状态", "GET", "/api/v1/increment-upload"],
  [
    "qa_list_build_upload_chains",
    "读取构建上传联动历史",
    "GET",
    "/api/v1/increment-upload/build-chains",
  ],
  ["qa_enqueue_upload", "提交增量上传任务", "POST", "/api/v1/increment-upload/jobs"],
  [
    "qa_enqueue_build_upload",
    "提交构建单包上传联动",
    "POST",
    "/api/v1/increment-upload/build-chains",
  ],
  ["qa_upload_login", "登录项目上传服务", "POST", "/api/v1/increment-upload/login"],
  ["qa_upload_logout", "退出项目上传服务", "POST", "/api/v1/increment-upload/logout"],
  ["qa_upload_check_auth", "检查项目上传服务认证", "POST", "/api/v1/increment-upload/check-auth"],
  ["qa_resume_upload", "恢复指定上传任务", "POST", "/api/v1/increment-upload/jobs/:id/resume"],
  [
    "qa_resume_queued_upload",
    "恢复排队上传任务",
    "POST",
    "/api/v1/increment-upload/jobs/:id/resume-queued",
  ],
  [
    "qa_confirm_upload_publish",
    "确认项目上传发布",
    "POST",
    "/api/v1/increment-upload/jobs/:id/confirm-publish",
  ],
  ["qa_cancel_upload", "取消项目上传任务", "POST", "/api/v1/increment-upload/jobs/:id/cancel"],
  ["qa_get_upload_logs", "读取项目上传日志", "GET", "/api/v1/increment-upload/jobs/:id/logs"],
  [
    "qa_cancel_build_upload",
    "取消构建上传联动",
    "POST",
    "/api/v1/increment-upload/build-chains/:id/cancel",
  ],
  [
    "qa_resume_build_upload",
    "恢复构建上传联动",
    "POST",
    "/api/v1/increment-upload/build-chains/:id/resume",
  ],
  ["qa_list_relay_outbox", "读取项目 Relay 投递与暂停记录", "GET", "/api/v1/production/outbox"],
  [
    "qa_resume_relay_outbox",
    "显式恢复项目 Relay 投递",
    "POST",
    "/api/v1/production/outbox/:id/resume",
  ],
  ["qa_get_relay_project", "读取项目 Relay 配置与执行器", "GET", "/api/v1/production/project"],
  ["qa_list_relay_tasks", "读取项目 Relay 任务", "GET", "/api/v1/production/tasks"],
  ["qa_list_relay_history", "读取各配置版本 Relay 历史", "GET", "/api/v1/production/tasks/history"],
  ["qa_get_relay_task", "读取指定 Relay 任务", "GET", "/api/v1/production/tasks/:id"],
  ["qa_get_relay_attachment", "读取指定 Relay 附件", "GET", "/api/v1/production/attachments/:id"],
  ["qa_list_relay_batches", "读取项目 Relay 批次", "GET", "/api/v1/production/batches"],
  ["qa_get_relay_batch", "读取项目 Relay 批次详情", "GET", "/api/v1/production/batches/:id"],
  ["qa_create_relay_batch", "创建项目 Relay 任务批次", "POST", "/api/v1/production/batches"],
  ["qa_upload_relay_attachment", "上传项目 Relay 附件", "POST", "/api/v1/production/uploads"],
  [
    "qa_retry_relay_batch",
    "重试项目 Relay 任务批次",
    "POST",
    "/api/v1/production/batches/:id/retry",
  ],
  ["qa_get_qingyu_history", "读取各版本轻语同步历史", "GET", "/api/v1/qingyu/history"],
  ["qa_get_qingyu_session", "读取项目轻语会话", "GET", "/api/v1/integrations/qingyu/session"],
  ["qa_start_qingyu_login", "启动项目轻语登录", "POST", "/api/v1/integrations/qingyu/login/start"],
  [
    "qa_get_qingyu_login_status",
    "读取轻语登录进度",
    "GET",
    "/api/v1/integrations/qingyu/login/status",
  ],
  ["qa_qingyu_logout", "退出项目轻语会话", "POST", "/api/v1/integrations/qingyu/logout"],
  [
    "qa_list_qingyu_projects",
    "读取项目轻语项目列表",
    "GET",
    "/api/v1/integrations/qingyu/projects",
  ],
  ["qa_list_qingyu_defects", "读取项目轻语订单", "GET", "/api/v1/integrations/qingyu/defects"],
  ["qa_import_qingyu_defects", "导入项目轻语订单", "POST", "/api/v1/integrations/qingyu/import"],
  ["qa_get_qingyu_link", "读取 Bug 轻语订单关联", "GET", "/api/v1/bugs/:bugId/integrations/qingyu"],
  [
    "qa_resolve_qingyu_link",
    "重试 Bug 轻语订单关闭同步",
    "POST",
    "/api/v1/bugs/:bugId/integrations/qingyu/resolve",
  ],
] as const;
